#!/bin/sh
bspc wm -O HDMI-1 LVDS-1        # reorder desktops
# move first 4 desktops
bspc desktop ^2:^1 -m ^1
bspc desktop ^2:^1 -m ^1
bspc desktop ^2:^1 -m ^1
bspc desktop ^2:^1 -m ^1
# remove default desktop before reset
bspc desktop ^1:^1 -r
# rename, add or remove desktops
bspc monitor ^1 -d I II III IV  # primary monitor
bspc monitor ^2 -d V VI         # secondary monitor

