#!/bin/sh
pacstrap /mnt                           \
    ark                                 \   # archiving tool for KDE
    dolphin                             \   # feature rich file manager for KDE
    print-manager                       \   # printer and print job manager for KDE
    gwenview                            \   # feature rich image viewer for KDE
    kcalc                               \   # scientific calculator for KDE
    kde-gtk-config                      \   # GTK2 and GTK3 configurator for KDE
    kdegraphics-thumbnailers            \   # thumbnails for media file formats
    kemoticons                          \   # support emoticons in KDE apps
    kfind                               \   # find files and directories
    kinfocenter                         \   # system information dialog for KDE
    kinit                               \   # process launcher to speed up launching KDE apps
    konsole                             \   # feature rich terminal emulator for KDE
    krunner                             \   # provide actions based on given string
    ksysguard                           \   # feature rich process manager for KDE
    kwin                                \   # KDE window manager
    latte-dock                          \   # feature rich dock for KDE
    networkmanager-qt                   \   # Qt GUI for networkmanager
    okular                              \   # feature rich document viewer for KDE
    partitionmanager                    \   # partition manager for KDE
    pavucontrol                         \   # adjuste pulsaudio settings
    plasma-desktop                      \   # KDE plasma desktop experience
    plasma-nm                           \   # networkmanager integration for plasma desktop
    plasma-pa                           \   # pulseaudio integration for plasma desktop
    plasma5-applets-redshift-control    \   # redshift integration for plasma desktop
    powerdevil                          \   # power management for plasma desktop
    sddm                                \   # display manager for KDE
    sddm-kcm                            \   # configuration module for SDDM
    spectacle                           \   # feature rich screenshot tool for KDE
    systemsettings                      \   # system settings dialog for KDE
    sweeper                             \   # system cleaner for KDE

# MacOS like KWIN decoration icons
git clone https://aur.archlinux.org/sierrabreeze-kwin-decoration-git.git
cd sierrabreeze-kwin-decoration-git && makepkg -si
cd ../ && rm -rf sierrabreeze-kwin-decoration-git/
