#!/bin/sh
DOTS=/data/re1/dotfiles

# create config folders if they do not exist
mkdir -p $DOTS/.config/i3
mkdir -p $DOTS/.config/termite
mkdir -p $DOTS/.config/tint2
mkdir -p $DOTS/.oh-my-zsh/custom

# copy config files to $DOTS
cp -R ~/.config/i3 $DOTS/.config/i3
cp -R ~/.config/termite $DOTS/.config/termite
cp -R ~/.config/tint2/tint2rc $DOTS/.config/tint2
cp ~/.oh-my-zsh/custom/greeter.sh $DOTS/.oh-my-zsh/custom/greeter.sh
cp ~/.i3blocks.conf $DOTS/.i3blocks.conf
cp ~/.vimrc $DOTS/.vimrc
cp ~/.zshrc $DOTS/.zshrc
# save installed packages
pacman -Qet > $DOTS/packages.txt
