#!/bin/sh
DOTS=/data/re1/dotfiles
# directories
FONTSCONFIG=.config/fontconfig
TERMITE=.config/termite
OHMYZSH=.oh-my-zsh/custom
# files
VIM=.vim

# create config folders if they do not exist
mkdir -p $DOTS/$FONTSCONFIG
mkdir -p $DOTS/$TERMITE
mkdir -p $DOTS/$OHMYZSH
mkdir -p $DOTS/$VIM

# copy config directories to $DOTS
cp -R ~/$FONTSCONFIG/* $DOTS/$FONTSCONFIG
cp -R ~/$TERMITE/* $DOTS/$TERMITE
# copy config files to $DOTS
cp -R ~/$VIM $DOTS/$VIM
cp ~/$OHMYZSH/greeter.sh $DOTS/.oh-my-zsh/custom/greeter.sh
cp ~/.vimrc $DOTS/.vimrc
cp ~/.zshrc $DOTS/.zshrc
# save installed packages
pacman -Qet > $DOTS/packages.txt
