#!/bin/sh
DOTS=$HOME/Projects/re1/dots

declare -a targets=(
    '.config/Code - OSS/User/settings.json' '.config/fontconfig' '.config/nvim' 
    '.config/systemd/user' '.vimrc' '.zshrc'
)

rm -rf $DOTS/.config $DOTS/.local

for target in "${targets[@]}"
do
    dir="$(dirname "${target}")"
    mkdir -p "$dir"
    cp -R "$HOME/$target" "$DOTS/$dir"
    echo "$HOME/$target → $DOTS/$dir"
done

# save installed packages
pacman -Qet > $DOTS/packages.txt
