#!/bin/sh

# create config folders if they do not exist
mkdir -p $ETC/.local/share/konsole
mkdir -p $ETC/.oh-my-zsh/custom
mkdir -p $ETC/.config/latte
mkdir -p $ETC/.local/share/konsole

# copy config files to $ETC
sudo cp ~/.vimrc $ETC/.vimrc
sudo cp ~/.zshrc $ETC/.zshrc
sudo cp ~/.local/share/konsole/base16-material-arc.colorscheme $ETC/.local/share/konsole/base16-material-arc.colorscheme
sudo cp ~/.oh-my-zsh/custom/greeter.sh $ETC/.oh-my-zsh/custom/greeter.sh
sudo cp ~/.config/latte/re1.layout.latte $ETC/.config/latte/re1.layout.latte
sudo cp ~/.local/share/konsole/re1.profile $ETC/.local/share/konsole/re1.profile

