#!/bin/sh

# create config folders if they do not exist
mkdir -p $ETC/.config/latte
mkdir -p $ETC/.local/share/konsole
mkdir -p $ETC/.oh-my-zsh/custom

# copy config files to $ETC
sudo cp ~/.config/kwinrc $ETC/kwinrc
sudo cp ~/.config/latte/re1.layout.latte $ETC/.config/latte/re1.layout.latte
sudo cp ~/.local/share/konsole/base16-material-arc.colorscheme $ETC/.local/share/konsole/base16-material-arc.colorscheme
sudo cp ~/.local/share/konsole/re1.profile $ETC/.local/share/konsole/re1.profile
sudo cp ~/.oh-my-zsh/custom/greeter.sh $ETC/.oh-my-zsh/custom/greeter.sh
sudo cp ~/.vimrc $ETC/.vimrc
sudo cp ~/.zshrc $ETC/.zshrc

