#!/bin/sh

feh --bg-fill ~/.background.png &
~/.config/Thunar/tumblerd &

if [ "$(autorandr --current)" = 'docked' ]
then
    bspc wm -O HDMI-1 LVDS-1
    
    bspc monitor ^1 -d 1 2 3 4
    bspc monitor ^2 -d 5 6
else
    bspc monitor -d 1 2 3 4 5 6
fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config top_padding 28

bspc config border_width 2

bspc config normal_border_color     \#2e3440
bspc config active_border_color     \#4c566a
bspc config focused_border_color    \#81a1c1

bspc config window_gap  12

bspc config split_ratio             0.618
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config presel_feedback_color   \#3b4252

bspc rule -a "" desktop=^5  # fix for spotify (https://github.com/baskerville/bspwm/issues/291)
bspc rule -a TelegramDesktop desktop=^5

bspc rule -a feh state=floating
bspc rule -a Gpick state=floating
bspc rule -a Viewnior state=floating
bspc rule -a vlc state=floating
