#!/bin/sh
bspc monitor -d 1 2 3 4 5 6

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config top_padding 28

bspc config border_width 2

bspc config normal_border_color     \#2f343f
bspc config active_border_color     \#ffd580
bspc config focused_border_color    \#73d0ff

bspc config window_gap  12

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config presel_feedback_color   \#3b4252

bspc rule -a "" desktop=^5  # fix for spotify (https://github.com/baskerville/bspwm/issues/291)
bspc rule -a TelegramDesktop desktop=^5

bspc rule -a feh state=floating
bspc rule -a Gpick state=floating
bspc rule -a Viewnior state=floating
bspc rule -a vlc state=floating
